language: node_js
node_js:
  - "0.8"
  - "0.9"
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"

os:
  - linux
  - osx

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang

# matrix:
#   allow_failures:
#     - os: osx
